#!/bin/sh

# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

DEVICE=wingray
MANUFACTURER=moto

BASE=../../../vendor/$MANUFACTURER/$DEVICE

mkdir -p $BASE

(cat << EOF) > $BASE/proprietary/Android.mk
# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURER/$DEVICE/setup-makefiles.sh

LOCAL_PATH := \$(call my-dir)

ifeq (\$(TARGET_DEVICE),$DEVICE)
EOF

for FILE in `grep -v -e ^# -e ^$ proprietary-blobs.txt | grep apk$ | sed -e 's#^/system/##g'`; do
    PACKAGE=`basename $FILE .apk`
    (cat << EOF) >> $BASE/proprietary/Android.mk

include \$(CLEAR_VARS)
LOCAL_MODULE := $PACKAGE
LOCAL_MODULE_OWNER := $MANUFACTURER
LOCAL_SRC_FILES := $FILE
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_TAGS := optional
LOCAL_CERTIFICATE := platform
LOCAL_MODULE_SUFFIX := \$(COMMON_ANDROID_PACKAGE_SUFFIX)
include \$(BUILD_PREBUILT)
EOF
done

(cat << EOF) >> $BASE/proprietary/Android.mk

endif
EOF

(cat << EOF) > $BASE/device-vendor-blobs.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURER/$DEVICE/setup-makefiles.sh

PRODUCT_COPY_FILES += \\
EOF

COUNT=`grep -v -e ^# -e ^$ -e apk$ proprietary-blobs.txt | wc -l | awk {'print $1'}`
END=" \\"
for FILE in `grep -v -e ^# -e ^$ -e apk$ proprietary-blobs.txt | sed -e 's#^/system/##g'`; do
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = '0' ]; then
        END=''
    fi
    echo "    vendor/$MANUFACTURER/$DEVICE/proprietary/$FILE:system/$FILE$END" >> $BASE/device-vendor-blobs.mk
done

(cat << EOF) >> $BASE/device-vendor-blobs.mk

PRODUCT_PACKAGES += \\
EOF

COUNT=`grep -v -e ^# -e ^$ proprietary-blobs.txt | grep apk$ | wc -l | awk {'print $1'}`
END=" \\"
for FILE in `grep -v -e ^# -e ^$ proprietary-blobs.txt | grep apk$`; do
    PACKAGE=`basename $FILE .apk`
    COUNT=`expr $COUNT - 1`
    if [ $COUNT = '0' ]; then
        END=''
    fi
    echo "    $PACKAGE$END" >> $BASE/device-vendor-blobs.mk
done

(cat << EOF) > $BASE/device-vendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURER/$DEVICE/setup-makefiles.sh

\$(call inherit-product, vendor/$MANUFACTURER/$DEVICE/device-vendor-blobs.mk)
EOF

(cat << EOF) > $BASE/BoardConfigVendor.mk
# Copyright (C) 2010 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/$MANUFACTURER/$DEVICE/setup-makefiles.sh
EOF
